### ISSUE TITLE
pytest support

### ISSUE THREAD

**Issue by vabc3** [christianhelle/autofaker#2]
This is a very helpful project. Cannot imagine there is no AutoFixture correspondence in python.

It would be more useful if there is pytest support:
```python
from autofaker import autodata
@autodata()
def test_2(tstr: str):
  pass
```

Output: `NotImplementedError: This way of creating anonymous objects are only supported from unit test`

**Comment by christianhelle** [comment]
Thanks for your kind words! This was a learning project for me while getting started with Python :)

I'll see what I can do regarding pytest

**Comment by christianhelle** [comment]
I started work on this and the branch [pytest-support](https://github.com/christianhelle/autofaker/tree/pytest-support) already supports the sample test you posted

```python
from autofaker import autodata
@autodata()
def test_create_str_using_decorator(text: str):
  assert text is not None
```

I'm adding a few more [comprehensive test cases](https://github.com/christianhelle/autofaker/tree/pytest-support/tests/pytests) so I'm sure I don't introduce breaking changes

**Comment by christianhelle** [comment]
@vabc3 I implemented this request and will release it to PyPi as soon as I update the docs, sample code, and resolve SonarCloud issues

**Comment by christianhelle** [comment]
This is now release to PyPi as [AutoFaker v0.4.9](https://pypi.org/project/autofaker/0.4.9/)

**Comment by vabc3** [comment]
Just tried the new release, it works perfectly.
Thanks for the great work, that's so cool.
